project: VibeCheck-HumanVSGpt
wandb: False # Set to True to log to Weights and Biases
output_name: human_vs_gpt
save_dir: pipeline_results
ranker: RelativeRanker

data_path: data/gpt_vs_human/multisource_testing_train.csv
test_data_path: data/gpt_vs_human/multisource_testing_test.csv
models: [human_answers, chatgpt_answers]

num_proposal_samples: 10
proposer_batch_size: 5

k: 3 # num clusters in reducer step
num_eval: 5
num_axes_generated: 20
judges: [gpt-4o-mini]
