project: VibeCheck-ChatbotArena
wandb: False # Set to True to log to Weights and Biases
num_samples: 150
output_name: filter_1_iter
num_final_eval: 10

save_dir: pipeline_results
data_path: data/vibe_control_arena.csv
test_data_path: False
models: [response_a, response_b]

filter_mm_only: True
k: 7
num_eval: 20
num_axes_generated: 50
ranker: RelativeRanker
reducer: AxisReducer
proposer: LLMProposerFixed
num_topic_clusters: 5
proposer_batch_size: 5

judges: [gpt-4o-mini]
eval_only: False
num_proposal_samples: 150
proposer_only: True
new_prompt: True
max_iterations: 1
axes: False

proposer_prompt: proposer_prompt_freeform_no_detail

# models
rubric_generation_model: "gpt-4o"
proposer_model: "gpt-4o"