project: VibeCheck-LiveBench-new
wandb: False # Set to True to log to Weights and Biases
num_samples: False
dummy_eval: False
oz: False
group_column: False
test: False
save_dir: pipeline_results
data_path: data/code/livebench_correct.csv

k: 3
batch_size: 50
num_axes_generated: 20
num_eval: 10
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical
ranker: RelativeRanker
# ranker: PreferenceRanker
sampler: Sampler
reducer: AxisReducer
proposer: LLMProposerFixed
num_topic_clusters: 5
proposer_batch_size: 1
judges: [gpt-4o-mini]
models: ['Claude', 'Mistral']
# ['friendly and personable', 'professional', 'casual', 'cold-and-factual', 'storyteller', 'organized', 'safety-concious', 'conspiracy-theorist', 'funny', 'imaginative', 'anotagonistic']
eval_only: False
num_proposal_samples: 40
# axes: ['Code Complexity and Style: High: Includes complex algorithms, advanced features, and idiomatic coding practices with a focus on optimization and modular functions. Low: Relies on simple algorithms, basic structures, and uses more inline or monolithic code with traditional practices.', 'Consistency and Quality: High: Demonstrates uniform approach, style, and naming with detailed, precise output formatting and consistent function usage. Low: Shows varied approaches, inconsistent naming, and minimal or default output formatting.', 'Efficiency and Optimization: High: Focuses on reducing redundancy through careful input handling, compact and efficient code, and optimization techniques. Low: Emphasizes readability, possibly at the expense of efficiency, using straightforward approaches and minimal optimization.', 'Flexibility and Maintainability: High: Adopts adaptive, flexible coding styles and granular, fine-grained logic allowing for easy updates and maintenance. Low: Utilizes rigid coding and broad, coarse-grained logic, hindering modifications.', 'Readability and Documentation: High: Code is well-structured and documented, making extensive use of clear, descriptive comments. Low: Code is compact, possibly sacrificing clarity, with sparse or vague documentation.']
# detail: True
axes: False
new_prompt: True

new_sample: True

# models
rubric_generation_model: "gpt-4o"
proposer_model: "gpt-4o"