project: VibeCheck-Summarization
wandb: False # Set to True to log to Weights and Biases
num_samples: False
dummy_eval: False
oz: False
group_column: False
test: False
save_dir: pipeline_results
# data_path: data/arena/gpt-4-0125-preview_vs_llama_turn1.csv
data_path: data/summarization/summ_cnndm_train_with_pref_exclude_ties.csv
test_data_path: data/summarization/summ_cnndm_test_with_pref_exclude_ties.csv
k: 5
batch_size: 50
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical 
ranker: RelativeRanker
sampler: Sampler
reducer: AxisReducer
proposer: LLMProposerFixed
num_topic_clusters: 10
proposer_batch_size: 5
# judges: [gpt-4o-mini, claude-3-haiku-20240307]
judges: [gpt-4o-mini]
models: [TNLGv2, command_xlarge_beta]
eval_only: False
axes: False
num_axes_generated: 20
num_proposal_samples: 10
new_prompt: True
proposer_prompt: proposer_prompt_freeform_summarization

num_eval: 10
num_final_eval: 10

# models
rubric_generation_model: "gpt-4o"
proposer_model: "gpt-4o"