project: VibeCheck-MATH-new # project name in wandb
wandb: True


# Exp Configs
max_iterations: 1 # number of iterations to run the pipeline
filter: True # filter out axes
filter_mm_only: True # filter out axes with p-values greater than 0.1 only for the model that is being compared to the MM
ridge_regression: False # add ridge regression to the ranker
lasso_regression: False # add lasso regression to the ranker
give_prev_axes: True # give the previous axes to the proposer during iteration step
dummy_preference: False # for debugging purposes
filter_p_values: False # filter out axes with p-values greater than 0.1
filter_pref_only: False 

# Data
# data_path: data/helm/claude_gpt_math_cot_test.csv
data_path: data/helm/claude_gpt_math_cot_combined.csv
test_data_path: False
output_name: claude_gemini # name of the output folder and wand run name
models: ['claude-3-5', 'gpt-4o'] # models your comparing (columns in your dataframe)
num_samples: False # amount of samples you use to evaluate the axes (userful for debugging)
num_eval_samples: False # same as above but for evaluation

# Evaluation
eval_only: False
early_stopping: False
early_stopping_threshold: 0.05
dummy_eval: False # for debugging purposes
num_eval: 3 # number of axes to evaluate
num_final_eval: 3 # number of axes to evaluate in the final evaluation (after all iterations)
eval_every_iteration: False # evaluate the axes every iteration on test set

# If set to false, then the axes will be discovered from the data. Otherwise you can set it to a list of preset axes
axes: ["Conciseness: High: Direct answers, minimal rephrasing. Low: Reiterates or elaborates unnecessarily",
# "Language Formality: High: Uses formal, academic tone. Low: Adopts informal, conversational tone.",
"Format Consistency: High: Maintains consistent formatting. Low: Displays inconsistent formatting.",
"Mathematical Justification: High: Explains principles and justifies steps. Low: Provides conclusions without justification.",
"Mathematical Symbols Usage: High: Employs formal symbols extensively. Low: Prefers simpler text representations.",
"Use of Mathematical Concepts: High: Elaborates on relevant concepts. Low: Provides solutions without concept explanations.",
"Clarity of Calculations: High: Uses clear, structured notation and organized steps. Low: Presents calculations with minimal structure.",
"Detail and Explanation: High: Provides thorough, step-by-step explanations with context. Low: Offers direct results with minimal explanation."]
# axes: ["Friendliness: High: Friendly and Interactive Low: Cold and Formal"]

