project: VibeCheck-Summarization
wandb: True # Set to True to log to Weights and Biases
num_samples: False
dummy_eval: False
test: False
output_name: vibecheck_summarization_1_iter
save_dir: pipeline_results

data_path: data/summarization/summ_cnndm_train_with_pref_exclude_ties.csv
test_data_path: data/summarization/summ_cnndm_test_with_pref_exclude_ties.csv
k: 5
batch_size: 50
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical 
ranker: RelativeRanker
sampler: Sampler
reducer: AxisReducer
proposer: LLMProposerFixed
num_topic_clusters: 10
proposer_batch_size: 2
judges: [gpt-4o-mini]
models: [TNLGv2, command_xlarge_beta]
eval_only: False
axes: False
num_axes_generated: 20
num_proposal_samples: 10
new_prompt: True
proposer_prompt: proposer_prompt_freeform_summarization


num_eval: False
num_final_eval: False

# models
rubric_generation_model: "gpt-4o"
proposer_model: "gpt-4o"